// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj3xUzP781M-m6CDen9GhNdSguppmcCCQ',
    appId: '1:67056759657:web:de1f42068d040caace83f8',
    messagingSenderId: '67056759657',
    projectId: 'skillswap-7a183',
    authDomain: 'skillswap-7a183.firebaseapp.com',
    storageBucket: 'skillswap-7a183.firebasestorage.app',
    measurementId: 'G-WV85PP5F4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRWzwg1ku06jsEq68LdPwU-jRRAuFQ4aM',
    appId: '1:67056759657:android:044e6aa5bde33c67ce83f8',
    messagingSenderId: '67056759657',
    projectId: 'skillswap-7a183',
    storageBucket: 'skillswap-7a183.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAo0Nv9NHwqg8dsQ2HsyDQyCR25X6vHxg',
    appId: '1:67056759657:ios:8c2fd45e7a8ac401ce83f8',
    messagingSenderId: '67056759657',
    projectId: 'skillswap-7a183',
    storageBucket: 'skillswap-7a183.firebasestorage.app',
    iosBundleId: 'com.skillswap.skillSwap',
  );
}
